export const groups = [
  {
    mounth: "Enero",
    groups: ["01", "02", "03"],
  },
  {
    mounth: "Marzo",
    groups: ["04"],
  },
  {
    name: "03",
    mounth: "Abril",
    groups: ["05", "06", "07"],
  },
  {
    name: "01",
    mounth: "Mayo",
    groups: ["08", "09"],
  },
];

export const residents = [
  {
    id: 1,
    name: "Flores López Kevin Daniel",
    controlNumber: "18280754",
    gender: "Hombre",
    semester: 9,
    phone: 7291754034,
    homePhone: 7291754034,
    proyectName: "Creacion de una aplicaicones para residentes",
    email: "kevin.kdfl@gmail.com",
    status: "Aceptado",
    group: "01",
  },
  {
    id: 2,
    name: "Zarate Garduño Pablo Daniel ",
    controlNumber: "18280785",
    gender: "Hombre",
    semester: 5,
    phone: 7291754465,
    homePhone: 7291754465,
    proyectName: "Esto es es cinee uff",
    email: "pabloDaniel1469@gmail.com",
    status: "Aceptado",
    group: "01",
  },
  {
    id: 3,
    name: "Cruz Soto Kenia",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 9,
    phone: 729175544,
    homePhone: 729175544,
    proyectName: "Creacion de una aplicacion react",
    email: "KeniaRico@gmail.com",
    status: "Rechazado",
    group: "01",
  },
  {
    id: 4,
    name: "Alvarez Cruz Alejandro",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 12,
    phone: 729175544,
    homePhone: 78542615,
    proyectName: "El lol de gana XD",
    email: "elpatronhh@gmail.com",
    status: "Aceptado",
    group: "01",
  },
  {
    id: 5,
    name: "Garcia Garcia Jose Jose",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 12,
    phone: 729121544,
    homePhone: 98789456,
    proyectName: "Recreacion de metodos numericos y su metodologia",
    email: "jose@gmail.com",
    status: "Rechazado",
    group: "02",
  },
  {
    id: 6,
    name: "Perez Gomez Lionel Messi",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 10,
    phone: 65465746,
    homePhone: 621654466,
    proyectName: "Documentacion sobre la robotoica y la inteligencia artifical",
    email: "messi@gmail.com",
    status: "Aceptado",
    group: "02",
  },
  {
    id: 7,
    name: "López Perez Monserrath",
    controlNumber: "18280742",
    gender: "Mujer",
    semester: 9,
    phone: 543656346,
    homePhone: 85441654,
    proyectName: "Creacion de una aplciaicon de escritorio empleando electron",
    email: "monseee@gmail.com",
    status: "Aceptado",
    group: "02",
  },
  {
    id: 8,
    name: "Guardia Jimenez Marta",
    controlNumber: "18280742",
    gender: "Mujer",
    semester: 9,
    phone: 72375544,
    homePhone: 567867867,
    proyectName: "Desarrollo de material nuclear",
    email: "MartaMartinex@gmail.com",
    status: "Aceptado",
    group: "03",
  },
  {
    id: 9,
    name: "Hernandez Flores Marco",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 11,
    phone: 74564544,
    homePhone: 34515413543,
    proyectName: "Investigacion sobre la materia negra",
    email: "marcooooooos@gmail.com",
    status: "Rechazado",
    group: "04",
  },
  {
    id: 10,
    name: "Guitierrez Jefe Fernando",
    controlNumber: "18280742",
    gender: "Hombre",
    semester: 12,
    phone: 123123123,
    homePhone: 54654654,
    proyectName: "Teoria de cuerdas",
    email: "ferchoooo@gmail.com",
    status: "Rechzado",
    group: "04",
  },
];
